add verification view
Laravel-Backpack/theme-coreuiv2 pull request #32
Opened 2023-08-29 14:26 UTC by pxpm

This PR should be merged when https://github.com/Laravel-Backpack/CRUD/pull/5301 gets merged.

![image](https://github.com/Laravel-Backpack/theme-coreuiv2/assets/7188159/7a49111e-8702-4f1f-98c3-9aa1c6a2eb7f)

2023-08-29 17:39 UTC, tabacitu commented
Eeh.... too wide for my taste 👀 

Why isn't this card narrower, like the one in the Tabler PR?

2023-08-29 21:31 UTC, pxpm commented
![image](https://github.com/Laravel-Backpack/theme-coreuiv2/assets/7188159/e4dceb14-4f23-4da5-b6e1-fdafe15562a2)

2023-08-30 10:15 UTC, tabacitu commented
Checked in browser too. Looks good now, thanks Pedro. Good to go imo!

2023-08-30 10:17 UTC, tabacitu requested changes

2023-08-30 10:17 UTC, tabacitu commented on resources/views/auth/verify-email.blade.php
> +    <div class="col-12 col-md-8 col-lg-4">
```suggestion
    <div class="col-12 col-md-8 col-lg-6">
```

2023-08-30 10:17 UTC, tabacitu commented on resources/views/auth/verify-email.blade.php
> +                    <div class="alert alert-success" role="alert">
```suggestion
                    <div class="alert alert-success my-0" role="alert">
```

2023-08-30 10:17 UTC, tabacitu commented on resources/views/auth/verify-email.blade.php
> +                <div class="mb-4 mt-2">
```suggestion
                <div class="mt-2">
```

2023-08-31 10:03 UTC, merged